title: Finality
description: Pushing Create to its limits with a side of adventure and combat.
theme: just-the-docs
color_scheme: vyre_theme

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
