title: Finality
description: Pushing Create to its limits with a side of adventure and combat.
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
